#define COLON 1
#define	SEMICOLON 2
#define IDENTIFIER 3
#define DELIMITER 4
#define INT_LITERAL 5
#define STR_LITERAL 6
#define COMMA 7
#define	BRACE 8
#define INT 10
#define LONG_INT 11
#define LONG_LONG_INT 12	
#define FLOAT 14
#define DOUBLE 15
#define LONG_DOUBLE 16
#define BOOL 17
#define IF 18
#define ELSE 19
#define ELSE_IF 20
#define WHILE 21
#define KEYWORD 22
#define CHAR 23
#define OPERATOR 24