#define COLON 1
#define	SEMICOLON 2
#define IDENTIFIER 3
#define DECIMAL 4
#define SCIENTIFIC 5
#define STR_LITERAL 6
#define COMMA 7
#define SCIENTIFIC_F 8
#define INT 10
#define LONG_INT 11
#define LONG_LONG_INT 12	
#define FLOAT 14
#define DOUBLE 15
#define LONG_DOUBLE 16
#define BOOL 17
#define IF 18
#define ELSE 19
#define ELSE_IF 20
#define WHILE 21
#define KEYWORD 22
#define CHAR 23
#define P_OPERATOR 24
#define U_OPERATOR 25
#define B_OPERATOR 26
#define T_OPERATOR 27
#define A_OPERATOR 28
#define ARRAY 29
#define COMMENT 30
#define ERR 31
#define I_OPERATOR 32
#define HEADER 33
#define DATATYPE 34
#define O_BRACE 35
#define C_BRACE 36
#define FPC	37
#define O_PAREN 38
#define C_PAREN 39
#define FUNCTION 40